# -*- coding: utf-8 -*-
"""Quotes Recommendation Chatbot Using NPL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17S28Wj--uxHNK2_eE67s2ovBuc0GCf0l
"""

# ---------------------------------------------------------
# PROJECT: HUMAN-CENTRIC SEMANTIC RECOMMENDATION ENGINE
# DEVELOPED BY: HIMANSHU PAWAR (B.Tech CSE)
# DOMAIN: ARTIFICIAL INTELLIGENCE & MACHINE LEARNING
# ---------------------------------------------------------

# 1. SETUP & INSTALLATION (Run this once)
import os
try:
    from sentence_transformers import SentenceTransformer, util
    import pandas as pd
    import torch
    import random
except ImportError:
    print("Installing required AI libraries... please wait.")
    os.system('pip install sentence-transformers pandas torch')
    from sentence_transformers import SentenceTransformer, util
    import pandas as pd
    import torch
    import random

# 2. INITIALIZE THE AI MODEL
# We use 'all-MiniLM-L6-v2' - a SOTA Transformer model for Semantic Similarity
print("Loading Neural Intelligence Engine...")
model = SentenceTransformer('all-MiniLM-L6-v2')

# 3. DIVERSE HUMAN-CENTRIC DATASET
# Mapped to a wide spectrum of human experiences to prevent repetitive answers
quotes_data = [
    {"text": "To handle yourself, use your head; to handle others, use your heart.", "tag": "Relationships"},
    {"text": "The purpose of our lives is to be happy.", "tag": "Happiness/Life"},
    {"text": "Everything has beauty, but not everyone sees it.", "tag": "Perspective"},
    {"text": "The only thing we have to fear is fear itself.", "tag": "Anxiety/Courage"},
    {"text": "What lies within us is greater than what lies behind us.", "tag": "Inner Strength"},
    {"text": "No one can make you feel inferior without your consent.", "tag": "Self-Worth"},
    {"text": "Kindness is the language which the deaf can hear.", "tag": "Empathy"},
    {"text": "To be yourself in a world trying to change you is an accomplishment.", "tag": "Identity"},
    {"text": "Failure is the opportunity to begin again more intelligently.", "tag": "Resilience"},
    {"text": "Small steps in the right direction can turn out to be the biggest steps.", "tag": "Motivation"},
    {"text": "Patience is bitter, but its fruit is sweet.", "tag": "Patience"},
    {"text": "Out of suffering have emerged the strongest souls.", "tag": "Growth"},
    {"text": "The best way to cheer yourself up is to try to cheer someone else up.", "tag": "Altruism"},
    {"text": "An unexamined life is not worth living.", "tag": "Self-Reflection"},
    {"text": "Your time is limited, don't waste it living someone else's life.", "tag": "Ambition"},
    {"text": "Love all, trust a few, do wrong to none.", "tag": "Human Ethics"},
    {"text": "The only limit to our realization of tomorrow is our doubts of today.", "tag": "Potential"},
    {"text": "Loneliness is the poverty of self; solitude is the richness of self.", "tag": "Solitude"}
]

df = pd.DataFrame(quotes_data)
# Pre-encode quotes into the vector space
quote_embeddings = model.encode(df['text'].tolist(), convert_to_tensor=True)

def get_perfect_recommendation(user_query):
    # Encode user input into a numerical vector
    user_embedding = model.encode(user_query, convert_to_tensor=True)

    # Calculate Cosine Similarity
    cosine_scores = util.cos_sim(user_embedding, quote_embeddings)[0]

    # Get Top 3 matches to ensure variety and prevent 'Single Quote' bug
    top_results = torch.topk(cosine_scores, k=min(3, len(df)))

    # Randomly select from top matches for a more 'natural' feel
    chosen_index = random.choice(top_results.indices.tolist())
    return df.iloc[chosen_index]

# 4. PROFESSIONAL INTERFACE
def start_chatbot():
    print("\n" + "="*65)
    print("      HUMAN-CENTRIC SEMANTIC AI RECOMMENDATION SYSTEM")
    print("           Developed by: Himanshu Pawar")
    print("="*65)
    print("System Status: Online | Model: SBERT | Domain: AI/ML")
    print("\nBot: Hello! I am trained to understand human thoughts and context.")
    print("How are you feeling today? (Type 'exit' to quit)")

    while True:
        user_input = input("\nYou: ").strip()

        if not user_input:
            continue

        if user_input.lower() in ['exit', 'quit', 'bye']:
            print(f"\nBot: Session Terminated. Great work today, Himanshu Pawar!")
            break

        try:
            match = get_perfect_recommendation(user_input)
            print(f"\n[AI Insight]: Match found in '{match['tag']}'")
            print(f"Quote: \"{match['text']}\"")
        except Exception as e:
            print(f"Bot: Error processing request. Please try again.")

if __name__ == "__main__":
    start_chatbot()